import type { Environment } from '@tagadapay/headless-sdk';

/**
 * Store config — read once at module init from Vite env vars.
 *
 * Set these in `.env` (auto-generated by `pnpm seed`):
 *
 *   VITE_STORE_ID=store_xxxxxx
 *   VITE_ENVIRONMENT=production
 *   VITE_GOOGLE_AUTOCOMPLETE_API_KEY=AIza... (optional)
 */
export const STORE_ID = import.meta.env.VITE_STORE_ID ?? '';

export const ENVIRONMENT: Environment =
  (import.meta.env.VITE_ENVIRONMENT as Environment | undefined) ?? 'production';

export const GOOGLE_AUTOCOMPLETE_API_KEY =
  import.meta.env.VITE_GOOGLE_AUTOCOMPLETE_API_KEY ?? '';

/** Brand identity — change these to match your store. */
export const BRAND = {
  name: 'NORTH',
  tagline: 'Considered apparel for every season.',
  emailReplyTo: 'hello@example.com',
} as const;

/** Free-shipping threshold for the marketing banner (in minor units, e.g. cents). */
export const FREE_SHIPPING_THRESHOLD_CENTS = 5000;
